configName: dsi_xlcdc_rgba8888_ws_9x75_curiosity_400x1280
folderName: legato_qs_9x75_curiosity_ws_7_9inch
format_version: v1.0
frameworkPath: C:\Harmony3
processor: SAM9X75D2G
projectName: legato_qs_9x75_curiosity_ws_7_9inch
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAM9X7_DFP\1.3.149
